# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83882cbff4579f7991f4c076f0c509ce7753aac36c66d56b2f49700567ce0bc47a0dff470e234dcd025e755288377138256bec638e62fc51d3df2d94b366f0f3

test:
  secret_key_base: f61f5cf5fa80d97ef73d6e2da8446cbdc6ed9541d1456894563005e6171b183799324d60c25e7f42c672ee85e93845bfae71ba104cb2b6699ab7ead1a3553199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
